import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className=" h-screen w-screen flex items-center justify-center">
      {children}
    </div>
  );
}
